name: orlandev_flutter_portafolio
version: 1.0.0+1
publish_to: none
description: My dev portafolio made in FLutter.
environment: 
  sdk: '>=2.19.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_storage: ^2.1.1
  logger: ^1.3.0
  get: 4.6.5
  flutter: 
    sdk: flutter
  octo_image: ^1.0.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/data/portfolio.json
  uses-material-design: true

